services:
  db:
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:17-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command:
      - 'postgres'
      - '-c'
      - 'port=${POSTGRES_PORT}'
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - server_net

  bot:
    container_name: bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE}
    build: .
    ports:
      - ${BOT_PORT}:${BOT_PORT}
    depends_on:
      - db
    networks:
      - server_net

volumes:
  db_vol: {}

networks:
  server_net:
    driver: bridge